spring:
    application:
        name: arch-layered-sample
    config:
        activate:
            on-profile: local
    main:
        allow-bean-definition-overriding: true
    output:
        ansi:
            enabled: always
    h2:
        console:
            enabled: true
            path: /h2-console
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE
        username: sa
        password:
    jpa:
        hibernate:
            ddl-auto: create
            naming:
                physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        properties:
            hibernate:
                format_sql: true
                use_sql_comments: true
        open-in-view: true
        show-sql: true
        defer-datasource-initialization: true
logging:
    level:
        root: info
        org.hibernate:
            SQL: info
            orm.jdbc.bind: trace
    pattern:
        console: "[%clr(%X{request_id:-startup}){cyan}] %d{yyyy-MM-dd HH:mm:ss.SSS} %clr(%5p){FATAL=red, ERROR=red, WARN=yellow, INFO=green, DEBUG=blue, TRACE=magenta} [%t] %clr(%-40.40logger{39}){cyan} [%4L] : %m%n"


